// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/dashcam.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeiMetadata_Gear int32

const (
	SeiMetadata_GEAR_PARK    SeiMetadata_Gear = 0
	SeiMetadata_GEAR_DRIVE   SeiMetadata_Gear = 1
	SeiMetadata_GEAR_REVERSE SeiMetadata_Gear = 2
	SeiMetadata_GEAR_NEUTRAL SeiMetadata_Gear = 3
)

// Enum value maps for SeiMetadata_Gear.
var (
	SeiMetadata_Gear_name = map[int32]string{
		0: "GEAR_PARK",
		1: "GEAR_DRIVE",
		2: "GEAR_REVERSE",
		3: "GEAR_NEUTRAL",
	}
	SeiMetadata_Gear_value = map[string]int32{
		"GEAR_PARK":    0,
		"GEAR_DRIVE":   1,
		"GEAR_REVERSE": 2,
		"GEAR_NEUTRAL": 3,
	}
)

func (x SeiMetadata_Gear) Enum() *SeiMetadata_Gear {
	p := new(SeiMetadata_Gear)
	*p = x
	return p
}

func (x SeiMetadata_Gear) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeiMetadata_Gear) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dashcam_proto_enumTypes[0].Descriptor()
}

func (SeiMetadata_Gear) Type() protoreflect.EnumType {
	return &file_proto_dashcam_proto_enumTypes[0]
}

func (x SeiMetadata_Gear) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeiMetadata_Gear.Descriptor instead.
func (SeiMetadata_Gear) EnumDescriptor() ([]byte, []int) {
	return file_proto_dashcam_proto_rawDescGZIP(), []int{0, 0}
}

type SeiMetadata_AutopilotState int32

const (
	SeiMetadata_NONE         SeiMetadata_AutopilotState = 0
	SeiMetadata_SELF_DRIVING SeiMetadata_AutopilotState = 1
	SeiMetadata_AUTOSTEER    SeiMetadata_AutopilotState = 2
	SeiMetadata_TACC         SeiMetadata_AutopilotState = 3
)

// Enum value maps for SeiMetadata_AutopilotState.
var (
	SeiMetadata_AutopilotState_name = map[int32]string{
		0: "NONE",
		1: "SELF_DRIVING",
		2: "AUTOSTEER",
		3: "TACC",
	}
	SeiMetadata_AutopilotState_value = map[string]int32{
		"NONE":         0,
		"SELF_DRIVING": 1,
		"AUTOSTEER":    2,
		"TACC":         3,
	}
)

func (x SeiMetadata_AutopilotState) Enum() *SeiMetadata_AutopilotState {
	p := new(SeiMetadata_AutopilotState)
	*p = x
	return p
}

func (x SeiMetadata_AutopilotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeiMetadata_AutopilotState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dashcam_proto_enumTypes[1].Descriptor()
}

func (SeiMetadata_AutopilotState) Type() protoreflect.EnumType {
	return &file_proto_dashcam_proto_enumTypes[1]
}

func (x SeiMetadata_AutopilotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeiMetadata_AutopilotState.Descriptor instead.
func (SeiMetadata_AutopilotState) EnumDescriptor() ([]byte, []int) {
	return file_proto_dashcam_proto_rawDescGZIP(), []int{0, 1}
}

// SEI (Supplemental Enhancement Information) metadata embedded in Tesla dashcam video streams.
type SeiMetadata struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	Version                  uint32                     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	GearState                SeiMetadata_Gear           `protobuf:"varint,2,opt,name=gear_state,json=gearState,proto3,enum=SeiMetadata_Gear" json:"gear_state,omitempty"`
	FrameSeqNo               uint64                     `protobuf:"varint,3,opt,name=frame_seq_no,json=frameSeqNo,proto3" json:"frame_seq_no,omitempty"`
	VehicleSpeedMps          float32                    `protobuf:"fixed32,4,opt,name=vehicle_speed_mps,json=vehicleSpeedMps,proto3" json:"vehicle_speed_mps,omitempty"`
	AcceleratorPedalPosition float32                    `protobuf:"fixed32,5,opt,name=accelerator_pedal_position,json=acceleratorPedalPosition,proto3" json:"accelerator_pedal_position,omitempty"`
	SteeringWheelAngle       float32                    `protobuf:"fixed32,6,opt,name=steering_wheel_angle,json=steeringWheelAngle,proto3" json:"steering_wheel_angle,omitempty"`
	BlinkerOnLeft            bool                       `protobuf:"varint,7,opt,name=blinker_on_left,json=blinkerOnLeft,proto3" json:"blinker_on_left,omitempty"`
	BlinkerOnRight           bool                       `protobuf:"varint,8,opt,name=blinker_on_right,json=blinkerOnRight,proto3" json:"blinker_on_right,omitempty"`
	BrakeApplied             bool                       `protobuf:"varint,9,opt,name=brake_applied,json=brakeApplied,proto3" json:"brake_applied,omitempty"`
	AutopilotState           SeiMetadata_AutopilotState `protobuf:"varint,10,opt,name=autopilot_state,json=autopilotState,proto3,enum=SeiMetadata_AutopilotState" json:"autopilot_state,omitempty"`
	LatitudeDeg              float64                    `protobuf:"fixed64,11,opt,name=latitude_deg,json=latitudeDeg,proto3" json:"latitude_deg,omitempty"`
	LongitudeDeg             float64                    `protobuf:"fixed64,12,opt,name=longitude_deg,json=longitudeDeg,proto3" json:"longitude_deg,omitempty"`
	HeadingDeg               float64                    `protobuf:"fixed64,13,opt,name=heading_deg,json=headingDeg,proto3" json:"heading_deg,omitempty"`
	LinearAccelerationMps2X  float64                    `protobuf:"fixed64,14,opt,name=linear_acceleration_mps2_x,json=linearAccelerationMps2X,proto3" json:"linear_acceleration_mps2_x,omitempty"`
	LinearAccelerationMps2Y  float64                    `protobuf:"fixed64,15,opt,name=linear_acceleration_mps2_y,json=linearAccelerationMps2Y,proto3" json:"linear_acceleration_mps2_y,omitempty"`
	LinearAccelerationMps2Z  float64                    `protobuf:"fixed64,16,opt,name=linear_acceleration_mps2_z,json=linearAccelerationMps2Z,proto3" json:"linear_acceleration_mps2_z,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SeiMetadata) Reset() {
	*x = SeiMetadata{}
	mi := &file_proto_dashcam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeiMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeiMetadata) ProtoMessage() {}

func (x *SeiMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dashcam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeiMetadata.ProtoReflect.Descriptor instead.
func (*SeiMetadata) Descriptor() ([]byte, []int) {
	return file_proto_dashcam_proto_rawDescGZIP(), []int{0}
}

func (x *SeiMetadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SeiMetadata) GetGearState() SeiMetadata_Gear {
	if x != nil {
		return x.GearState
	}
	return SeiMetadata_GEAR_PARK
}

func (x *SeiMetadata) GetFrameSeqNo() uint64 {
	if x != nil {
		return x.FrameSeqNo
	}
	return 0
}

func (x *SeiMetadata) GetVehicleSpeedMps() float32 {
	if x != nil {
		return x.VehicleSpeedMps
	}
	return 0
}

func (x *SeiMetadata) GetAcceleratorPedalPosition() float32 {
	if x != nil {
		return x.AcceleratorPedalPosition
	}
	return 0
}

func (x *SeiMetadata) GetSteeringWheelAngle() float32 {
	if x != nil {
		return x.SteeringWheelAngle
	}
	return 0
}

func (x *SeiMetadata) GetBlinkerOnLeft() bool {
	if x != nil {
		return x.BlinkerOnLeft
	}
	return false
}

func (x *SeiMetadata) GetBlinkerOnRight() bool {
	if x != nil {
		return x.BlinkerOnRight
	}
	return false
}

func (x *SeiMetadata) GetBrakeApplied() bool {
	if x != nil {
		return x.BrakeApplied
	}
	return false
}

func (x *SeiMetadata) GetAutopilotState() SeiMetadata_AutopilotState {
	if x != nil {
		return x.AutopilotState
	}
	return SeiMetadata_NONE
}

func (x *SeiMetadata) GetLatitudeDeg() float64 {
	if x != nil {
		return x.LatitudeDeg
	}
	return 0
}

func (x *SeiMetadata) GetLongitudeDeg() float64 {
	if x != nil {
		return x.LongitudeDeg
	}
	return 0
}

func (x *SeiMetadata) GetHeadingDeg() float64 {
	if x != nil {
		return x.HeadingDeg
	}
	return 0
}

func (x *SeiMetadata) GetLinearAccelerationMps2X() float64 {
	if x != nil {
		return x.LinearAccelerationMps2X
	}
	return 0
}

func (x *SeiMetadata) GetLinearAccelerationMps2Y() float64 {
	if x != nil {
		return x.LinearAccelerationMps2Y
	}
	return 0
}

func (x *SeiMetadata) GetLinearAccelerationMps2Z() float64 {
	if x != nil {
		return x.LinearAccelerationMps2Z
	}
	return 0
}

var File_proto_dashcam_proto protoreflect.FileDescriptor

const file_proto_dashcam_proto_rawDesc = "" +
	"\n" +
	"\x13proto/dashcam.proto\"\x86\a\n" +
	"\vSeiMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x120\n" +
	"\n" +
	"gear_state\x18\x02 \x01(\x0e2\x11.SeiMetadata.GearR\tgearState\x12 \n" +
	"\fframe_seq_no\x18\x03 \x01(\x04R\n" +
	"frameSeqNo\x12*\n" +
	"\x11vehicle_speed_mps\x18\x04 \x01(\x02R\x0fvehicleSpeedMps\x12<\n" +
	"\x1aaccelerator_pedal_position\x18\x05 \x01(\x02R\x18acceleratorPedalPosition\x120\n" +
	"\x14steering_wheel_angle\x18\x06 \x01(\x02R\x12steeringWheelAngle\x12&\n" +
	"\x0fblinker_on_left\x18\a \x01(\bR\rblinkerOnLeft\x12(\n" +
	"\x10blinker_on_right\x18\b \x01(\bR\x0eblinkerOnRight\x12#\n" +
	"\rbrake_applied\x18\t \x01(\bR\fbrakeApplied\x12D\n" +
	"\x0fautopilot_state\x18\n" +
	" \x01(\x0e2\x1b.SeiMetadata.AutopilotStateR\x0eautopilotState\x12!\n" +
	"\flatitude_deg\x18\v \x01(\x01R\vlatitudeDeg\x12#\n" +
	"\rlongitude_deg\x18\f \x01(\x01R\flongitudeDeg\x12\x1f\n" +
	"\vheading_deg\x18\r \x01(\x01R\n" +
	"headingDeg\x12;\n" +
	"\x1alinear_acceleration_mps2_x\x18\x0e \x01(\x01R\x17linearAccelerationMps2X\x12;\n" +
	"\x1alinear_acceleration_mps2_y\x18\x0f \x01(\x01R\x17linearAccelerationMps2Y\x12;\n" +
	"\x1alinear_acceleration_mps2_z\x18\x10 \x01(\x01R\x17linearAccelerationMps2Z\"I\n" +
	"\x04Gear\x12\r\n" +
	"\tGEAR_PARK\x10\x00\x12\x0e\n" +
	"\n" +
	"GEAR_DRIVE\x10\x01\x12\x10\n" +
	"\fGEAR_REVERSE\x10\x02\x12\x10\n" +
	"\fGEAR_NEUTRAL\x10\x03\"E\n" +
	"\x0eAutopilotState\x12\b\n" +
	"\x04NONE\x10\x00\x12\x10\n" +
	"\fSELF_DRIVING\x10\x01\x12\r\n" +
	"\tAUTOSTEER\x10\x02\x12\b\n" +
	"\x04TACC\x10\x03B\x17Z\x15teslaxy/backend/protob\x06proto3"

var (
	file_proto_dashcam_proto_rawDescOnce sync.Once
	file_proto_dashcam_proto_rawDescData []byte
)

func file_proto_dashcam_proto_rawDescGZIP() []byte {
	file_proto_dashcam_proto_rawDescOnce.Do(func() {
		file_proto_dashcam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dashcam_proto_rawDesc), len(file_proto_dashcam_proto_rawDesc)))
	})
	return file_proto_dashcam_proto_rawDescData
}

var file_proto_dashcam_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_dashcam_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_dashcam_proto_goTypes = []any{
	(SeiMetadata_Gear)(0),           // 0: SeiMetadata.Gear
	(SeiMetadata_AutopilotState)(0), // 1: SeiMetadata.AutopilotState
	(*SeiMetadata)(nil),             // 2: SeiMetadata
}
var file_proto_dashcam_proto_depIdxs = []int32{
	0, // 0: SeiMetadata.gear_state:type_name -> SeiMetadata.Gear
	1, // 1: SeiMetadata.autopilot_state:type_name -> SeiMetadata.AutopilotState
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_dashcam_proto_init() }
func file_proto_dashcam_proto_init() {
	if File_proto_dashcam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dashcam_proto_rawDesc), len(file_proto_dashcam_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dashcam_proto_goTypes,
		DependencyIndexes: file_proto_dashcam_proto_depIdxs,
		EnumInfos:         file_proto_dashcam_proto_enumTypes,
		MessageInfos:      file_proto_dashcam_proto_msgTypes,
	}.Build()
	File_proto_dashcam_proto = out.File
	file_proto_dashcam_proto_goTypes = nil
	file_proto_dashcam_proto_depIdxs = nil
}
